version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    depends_on:
      - backend
    expose:
      - 8080


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=food
      - WAITRESS_THREADS=8
    depends_on:
      - mongodb
    expose:
      - 5000


  mongodb:
    image: mongo:4.4
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: